language: C++
os: linux
dist: trusty
sudo: required
before_install:
- sudo .travis/register_apt_repositories.sh
- sudo apt-get install -y cross-mint-essential dos2unix lftp
- git --version
- make --version
- ld --version
- gcc --version
- m68k-atari-mint-ld --version
- m68k-atari-mint-gcc --version
- m68k-atari-mint-c++ --version
- tar --version
- unix2dos --version
- lftp --version
- wget https://github.com/mfro0/libcmini/releases/download/v0.48/libcmini-0.48.tar.gz -O /tmp/libcmini-0.48.tar.gz
- mkdir -p ../libcmini/build
- pushd ../libcmini/build && tar -xvf /tmp/libcmini-0.48.tar.gz && ln -sf lib/startup.o . && ln -sf lib/libcmini.a l && popd

script:
- make clean
- make strip
- make release
before_deploy: 
deploy:
  provider: releases
  api_key:
    secure: JJmcRyP2TadAm7KrjzRga/N022Bq0KiLMD8b7/Ho/Y7ctwxcoGpq9VqUih0wDupPnjw/50rT7Ige6UwehOKxzsTk+dPLklqzBlAH1n1DT00hHHe216s8p0GAfsCe3y09dfFUdynyy2zniH6//hB+ZyC1DGmZflg5x5mnTKjSGwrtbjLhUCSs5yO20Oo3HSpeuhEhqy33/5E0G0WaR5rYS7LNjIqvC7Vl5ovMhWuNdelfcPC2g2hFIcfKpy3GTVhOk88pF+aB3ZgcjnvMie2zNotWpKlDQMtIOUl/AF+z+PehevEgbfa63Y9We41KnHfOdPHdYxA/x9IyHf22uMGfldN6r08aXzjoCFE3fcqRs6c/fkMZd3WqWhtYYSuF539eaZFq16bUIiAsXYLgtbrWZjzpYhfuw2ESanr29LLP9w9O5enZfBIRSenRStX9V42Xl8Dwbo6DRWIel9Q32VsDynKXtlskhpi/lqHaTIILWvX8DiZ1ZWRTuUwIkDwDtzybt5AxQccphQzZMNg9AjqWlmELEYjsEefqTuBtWXfRDWogql+sMMvhlLLC/e87mDqPCyiw04QdQWElweczeBgkMEduxI69wM3MW5o2IVrww9ZTfPzzGbjlO+lYwAgYLT/3ER/JWcc3duitXdgRZ7mrUSF6hn6/1x9g8a7B549m64M=
  skip_cleanup: true
  file_glob: true
  file: libcmini-cplusplus.tar.gz
  overwrite: true
  on:
    tags: true
    repo: mfro0/libcmini-cplusplus
    all_branches: true
